### ISSUE TITLE
Adding New Servers to vpn application

### ISSUE THREAD

**Issue by FriendlyPug** [shanesreal/student-dashboard#1]
Hey man how can i add extra vpn servers to my vpn application ive done the servers i just need to code my program to add more servers if u could help pls dm me on Discord.
Discord: Friendly Pug#0001
Pls Help I would very much appriciate it i dont know much coding but if u could just help that would be very nice of u im making a vpn called LunaVPN

**Comment by shanesreal** [comment]
Hi, I just added the ability to connect to multiple servers you can checkout the updated code [here](https://github.com/shanesreal/vpn-application/tree/server_support)

https://user-images.githubusercontent.com/46653995/123547528-22126e00-d72f-11eb-861e-bdf11a2e4276.mp4

https://user-images.githubusercontent.com/46653995/123548688-d44c3480-d733-11eb-8a27-8d8fa3fa2cc0.mp4

**Comment by FriendlyPug** [comment]
> Hi, I just added the ability to connect to multiple servers you can checkout the updated code [here](https://github.com/shanesreal/vpn-application/tree/server_support)
> 
>  add_new_servers.mp4 
>  connect_to_server.mp4
Thanks so much man

**Comment by FriendlyPug** [comment]
Also what do i do when i clone it because it just gives me the same code as i had before for me its no different to the the other one u did 2 years ago

**Comment by shanesreal** [comment]
You can download the server_support branch with this git command:

`git clone -b server_support https://github.com/shanesreal/vpn-application`

I didn't want to merge it into the master branch because it could confuse people who watched the video, also all I did was concatenate the text string from the combobox so you might have to update the name of your .ovpn config files to match.
